---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
provisioner:
  name: ansible
  options:
    become: true
    diff: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
